# Generated by Django 5.0.6 on 2024-08-01 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcorn_api', '0002_alter_seguidor_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguidor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seguidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguidor',
            name='usuario_seguido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_seguido', to=settings.AUTH_USER_MODEL),
        ),
    ]
